export const courseConfig: Record<string, { displayName: string; color: string }> = {
  "mathematics": { displayName: "Mathematics", color: "#F26946" },
  "english": { displayName: "English", color: "#4ECDC4" },
  "basic science": { displayName: "Basic Science", color: "#45B7D1" },
  "basic technology": { displayName: "Basic Technology", color: "#F9A826" },
  "social studies": { displayName: "Social Studies", color: "#E84855" },
  "civic education": { displayName: "Civic Education", color: "#7D70BA" },
  "business studies": { displayName: "Business Studies", color: "#2A9D8F" },
  "home economics": { displayName: "Home Economics", color: "#E76F51" },
  "agricultural science": { displayName: "Agricultural Science", color: "#2A9D8F" },
  "physical education": { displayName: "Physical Education", color: "#E63946" },
  "computer studies": { displayName: "Computer Studies", color: "#3A86FF" },
  "creative arts": { displayName: "Creative Arts", color: "#8338EC" },
  "music": { displayName: "Music", color: "#FB5607" },
  "physics": { displayName: "Physics", color: "#F06595" },
  "chemistry": { displayName: "Chemistry", color: "#339AF0" },
  "biology": { displayName: "Biology", color: "#51CF66" },
  "further mathematics": { displayName: "Further Mathematics", color: "#FF922B" },
  "economics": { displayName: "Economics", color: "#CC5DE8" },
  "accounting": { displayName: "Accounting", color: "#20C997" },
  "commerce": { displayName: "Commerce", color: "#FDA7DF" },
  "government": { displayName: "Government", color: "#D980FA" },
  "literature": { displayName: "Literature", color: "#B53471" },
  "history": { displayName: "History", color: "#EE5A24" },
  "geography": { displayName: "Geography", color: "#A3CB38" },
  "fine arts": { displayName: "Fine Arts", color: "#FFC312" },
  "computer science": { displayName: "Computer Science", color: "#1289A7" },
  "french": { displayName: "French", color: "#6F1E51" },
};